version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - pg-network
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - pg-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pg-network:
    driver: bridge