// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db_generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Banner struct {
	ID      pgtype.UUID
	Name    string
	Image   string
	Cpm     pgtype.Numeric
	Geo     string
	Feature int32
}
